// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReleaseCand.Models;

namespace ReleaseCand.Migrations
{
    [DbContext(typeof(ReleaseCandContext))]
    [Migration("20181211211438_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReleaseCand.Models.OnOrd", b =>
                {
                    b.Property<int>("OnOrdID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BillAddress");

                    b.Property<string>("BillCity");

                    b.Property<string>("BillState");

                    b.Property<string>("BillZip");

                    b.Property<string>("CCV");

                    b.Property<bool>("CheeseBurger");

                    b.Property<bool>("CheeseCake");

                    b.Property<string>("CreditCardNum");

                    b.Property<string>("Email");

                    b.Property<DateTime>("ExpDate");

                    b.Property<string>("FirstName");

                    b.Property<bool>("FrenchFries");

                    b.Property<bool>("Lasagna");

                    b.Property<string>("LastName");

                    b.Property<bool>("Pepsi");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("Sprite");

                    b.Property<bool>("TiriMisu");

                    b.Property<bool>("Water");

                    b.HasKey("OnOrdID");

                    b.ToTable("OnOrd");
                });
#pragma warning restore 612, 618
        }
    }
}
